### ISSUE TITLE
"Kitchen sink" metapackage

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-javascript#101]
It may be useful to have a metapackage that includes all the plugins that we currently offer, for users that want all the functionality at the cost of increased bundle size.

**Comment by tombruijn** [comment]
@xadamy did you decide if you want to do this or not? Is it in the research phase?

**Comment by xadamy** [comment]
@tombruijn Planned for next week!

**Comment by tombruijn** [comment]
@xadamy great! But can you describe the issue in such a way that we know the action points? Now we weren't sure if this was a question to be answered with additional research or if you were going to pick this up already.
