### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by ellyaaisyah** [appsignal/appsignal-javascript#185]
_"Think of your bug report like a good tweet: You want it short, sweet, and to the point."_ 🐞

**Describe the bug**
TypeError: Converting circular structure to JSON on @appsignal/plugin-breadcrumbs-console
Cannot stringify JSON object.

**Comment by xadamy** [comment]
Hi @ellyaaisyah, thanks for reporting this. Do you know what the data you're passing as the argument here?

What you're seeing is the effect of this line:

```
typeof arg === "string" ? arg : JSON.stringify(arg))
```

If the argument is not a `string`, we naively parse the argument with `JSON.stringify`. If you can help me with the kind of data you're trying to process here, I can probably come up with a better way to handle this. Thanks!

**Comment by xadamy** [comment]
Hey @ellyaaisyah, was this issue solved for you? If so, or if I don't hear from you in the next week, I will close this issue for now.
