### ISSUE TITLE
It'd be great if passing an undefined key could get it to log errors to the console for development usage

### ISSUE THREAD

**Issue by Haegin** [appsignal/appsignal-javascript#208]
I'm trying to add Appsignal to our frontend app but I don't want to call out to appsignal when running in development. Currently the key is required. If I wrap the initialisation in a conditional I then need to stub the appsignal client with something that ignores any calls to it, and when creating and adding to spans that gets quite complicated.

Ideally passing an undefined key would switch it into development mode where it'd log the errors to the console instead of calling out to Appsignal. This is useful for development and the console would be one of the first places to check if someone is trying to debug errors not showing up in Appsignal so it wouldn't hide the problem.

Alternatively it could just silently discard the errors. This would be fine for not having to provide a key in development but it'd be hard to work out why errors aren't appearing in appsignal if someone misconfigured the client.

**Comment by xadamy** [comment]
@Haegin Thanks for your feedback on this! 🎉 This, to me, sounds like a good idea. Pinging my colleagues @thijsc @jeffkreeftmeijer for their thoughts.

**Comment by thijsc** [comment]
I think it is a good idea if you can call all the relevant functions without having initialized. That way people can leave all their error tracking hooks in if AppSignal is disabled.

**Comment by Haegin** [comment]
Thanks for implementing this, I'm looking forward to trying it out.
