### ISSUE TITLE
Breadcrumbs support

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-javascript#24]

**Comment by tombruijn** [comment]
@thijsc @xadamy can you elaborate on this project? And make a plan for building it. Let's also think about the UI for this before we start implementing it in the library.

**Comment by tombruijn** [comment]
Adam's going to look at a way to display this in the UI on AppSignal.com

**Comment by xadamy** [comment]
[Tracking issue for UI components.](https://github.com/appsignal/appsignal-server/issues/4851)
