### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by groe** [appsignal/appsignal-javascript#257]
Is there a changelog for this library, to support the upgrade process?

**Comment by xadamy** [comment]
@groe The CHANGELOG for `@appsignal/javascript` can be found [here](https://github.com/appsignal/appsignal-javascript/blob/develop/packages/javascript/CHANGELOG.md).

**Comment by groe** [comment]
@xadamy Thanks - that's helpful! May I suggest to add a link from the root of the repository too, where most users would probably look for it?
