### ISSUE TITLE
plugin-breadcrumbs-network: URL whitelist/blacklist

### ISSUE THREAD

**Issue by leiit** [appsignal/appsignal-javascript#259]
Currently the network plugin is logging all requests and there's no way to customize that. We'd like to omit requests going outside our own domain, from e.g. analytics scripts since these provide no value for us and just clutter the saved error report. 

This could be a simple configuration option accepting e.g. an array of domains / glob patterns / regexes to whitelist/blacklist.

**Comment by xadamy** [comment]
@leiit Thanks for the suggestion, and I agree, we should have this feature. I'll try and get something working for this by the end of next week!
