### ISSUE TITLE
Test suite improvements

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-javascript#278]
- [x] Move from TravisCI to SemaphoreCI
- [ ] BrowserStack in-browser integration tests ([Testem](https://github.com/testem/testem), [TestCafe](https://devexpress.github.io/testcafe/))
- [x] Improve coverage

**Comment by tombruijn** [comment]
Will be picked up in:

- https://github.com/appsignal/appsignal-javascript/issues/504
- https://github.com/appsignal/appsignal-javascript/issues/505
