### ISSUE TITLE
Weird TypeError "Cannot set property onunhandledrejection of [object Object] which has only a getter"

### ISSUE THREAD

**Issue by Calamari** [appsignal/appsignal-javascript#280]
**Describe the bug**
Our Appsinal is showing this error, and no clue where this is happening, the backtrace also shows none of our code, so I guess this is originating in AppSignal.

**Message**

```
  Cannot set property onunhandledrejection of [object Object] which has only a getter
```

**Backtrace (last 10 lines)**

```
TypeError: Cannot set property onunhandledrejection of [object Object] which has only a getter
webpack:///./node_modules/@appsignal/plugin-window-events/dist/esm/index.js:62:16 onunhandledrejection
webpack:///./node_modules/@appsignal/javascript/dist/esm/index.js:81:15 call
webpack:///./app/javascript/services/appsignal.js:27:13 use
webpack:///./app/javascript/services/appsignal.js:80:19 getInstance
webpack:///webpack/bootstrap:78:21 call
:4:15
webpack:///webpack/bootstrap:78:21 call
:13:15
webpack:///webpack/bootstrap:78:21 call
```

View on AppSignal: https://appsignal.com/bd427032-bdc3-4269-a25d-095736524828/sites/58e1fbb07478201647abdfb0/exceptions/incidents/385?timestamp=2020-04-24T12:54:03Z

**Comment by xadamy** [comment]
@Calamari Thanks for reporting! You're right that it's coming from within `Appsignal`, looks like `window.onunhandledrejection` isn't available in that environment, but I see no reason why it wouldn't be - it looks like Chrome 80. Let me look into this in more detail. From a cursory Google search, this seems to be related to Angular.

If you'd like to disable this behavior for now until I land a fix, you can do the following:

```
appsignal.use(plugin({
    onunhandledrejection: false
}))
```

**Comment by Calamari** [comment]
We are using appsignal with the react implementation. Maybe that helps to know.

**Comment by xadamy** [comment]
@Calamari Thanks for the clarification, the Angular thing is a red herring, then. Can you try bumping your package versions to the latest available version? Not 100% sure that this will fix anything, but worth a shot whilst I try and work out what's going on here.

**Comment by Calamari** [comment]
I'll try, I'll update @appsignal/javascript from 1.1.2 to 1.2.1.

**Comment by Calamari** [comment]
I just noticed that all the links in the backlog-helper comment above do not work.
![Screenshot_2020-05-28_14-04-43](https://user-images.githubusercontent.com/149719/83139192-40e99f80-a0ec-11ea-805d-7dc78419b534.png)

**Comment by Calamari** [comment]
But about this comment, I haven't noticed that problem since upgrading.

**Comment by tombruijn** [comment]
> I just noticed that all the links in the backlog-helper comment above do not work.

Hi @Calamari, you can ignore the Backlog helper. It's only relevant for the AppSignal team. All the links are to private repos.

**Comment by xadamy** [comment]
Closing this issue as @Calamari has reported not seeing it in a while. Please feel free to re-open if this becomes a problem again!
