### ISSUE TITLE
Max body size on axios client in webpack plugin

### ISSUE THREAD

**Issue by thijsc** [appsignal/appsignal-javascript#316]
We received a report in support that it's not possible to upload sourcemaps that are bigger than 10mb, you get this error message:

```
AppSignal Plugin: Error: Request body larger than maxBodyLength limit
```

This seems to be a limit that's configured in Axios using `maxBodyLength`. The max on the serverside at the moment is 16mb, so we could keep these values in sync.

**Comment by jeffkreeftmeijer** [comment]
Requested via [support](https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/27081224989) (private Intercom link).
