### ISSUE TITLE
React Native integration

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-javascript#36]

**Comment by MrTin** [comment]
Sorry for posting in an closed issue but I think it’s relevant if someone else finds their way here the same way I did. Might I suggest you add a dedicated link inside your docs for React Native and just reference to the React docs? Reasoning; I was researching different tools to accommodate our needs and in error I quickly ruled out AppSignal as I didn’t see any reference to Native. Good thing I really like you guys and kept searching for a bit longer until I found this, sounds like it just works? Will give it a try :)
