### ISSUE TITLE
Update action names for integrations

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-javascript#39]
@tombruijn raised [this comment](https://github.com/appsignal/appsignal-javascript/pull/21#discussion_r307157138) regarding action names for the integrations: 

> We support transactions without an action name. And default to "unknown" in some cases. So something like "UnknownAngularAction" would work, but I'd probably prefer no action name by default.

This means all the current integrations will need to be updated to not send an action name by default.

**Comment by tombruijn** [comment]
@xadamy  Is there a decision that needs to be made on this with the rest of the team? Or are you going to pick this up already?

**Comment by tombruijn** [comment]
Let's not set action names, as is the default for Ruby and Elixir.
