### ISSUE TITLE
Webpack plugin incompatible with Webpack 5

### ISSUE THREAD

**Issue by fdev** [appsignal/appsignal-javascript#435]
The [webpack plugin](https://github.com/appsignal/appsignal-javascript/tree/develop/packages/webpack) uses the `afterEmit` compile hook of Webpack to process the list of compiled assets.

In Webpack v4.29 (released Jauary 20th 2019) the [`output.futureEmitAssets` config option](https://webpack.js.org/configuration/output/#outputfutureemitassets) was added and `SizeOnlySource` asset objects were introduced that improve performance but lack functions like `existsAt` that your plugin relies on.

These new asset objects are used by default, unless `output.futureEmitAssets` is set to `false`, and will result in the following error:

```
[AppsignalPlugin]: unable to delete 'static/js/main.abcdefgh.chunk.js.map'
File does not exist. it may not have been created due to a build error.
```

However, this config option was [removed in Webpack 5](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#sizeonlysource-after-emit) and a `SizeOnlySource` asset object is now always used, making your plugin incompatible with Webpack 5.

Related: https://github.com/webpack/webpack/issues/8883

**Comment by zbarbuto** [comment]
Just to add to this as a bit of a warning: if you disable the `futureEmitAssets` option then although the AppSignal upload will start working, however the `deleteAfterCompile` will stop working (source map files will still exist after upload).

**Comment by xadamy** [comment]
Hey there @fdev , apologies for the long wait for a reply, I've been on holiday for the past couple of weeks so I've been unable to test this with Webpack 5 yet. I have made this a top priority for me to fix, and I'll update this issue as soon as I have any further updates, hopefully within the next few days or so.
