### ISSUE TITLE
Tags passed in react error boundary are not forwarded to appsignal report

### ISSUE THREAD

**Issue by hayfever** [appsignal/appsignal-javascript#441]
**Describe the bug**
Trying to pass tags into the react appsignal error boundary but they aren't being included in reports.

**To Reproduce**
Add appsignal error boundary in react app
Raise an error
No tags aside from `framework: "React"` are included

**Expected behavior**
Included tags would be present

**Additional context**

It looks like code for this has been added in the source but hasn't been released? I can see in https://github.com/appsignal/appsignal-javascript/blob/827222a7e6f754faf6cb873cf74d0149e49ef5ab/packages/react/src/ErrorBoundary.tsx#L19 there is a tag spread but looking in local node modules it doesn't seem to be present.

Thanks!

**Comment by xadamy** [comment]
@hayfever Whoops! You're right, looks like this had not been released. I have now released this as `@appsignal/react@1.0.2`. 👍
