### ISSUE TITLE
Webpack Plugin Uploads Invalid Source Map

### ISSUE THREAD

**Issue by zbarbuto** [appsignal/appsignal-javascript#461]
**Describe the bug**
Uploading source maps using the webpack plugin in an angular app result in bad json errors in AppSignal

![image](https://user-images.githubusercontent.com/9100419/103642107-9cdda600-4fa2-11eb-8b57-d4320ce032fe.png)

Uploading the same maps manually via CURL does not have the same issue.

**To Reproduce**

1. Setup the following custom webpack config js in a blank angular application:

```
const { AppsignalPlugin } = require('@appsignal/webpack');

module.exports = {
  plugins: [
    new AppsignalPlugin({
      apiKey: 'ApiKeyHere'
      release: 'RevisionHere'
      appName: 'AppNameHere',
      environment: 'development',
      urlRoot: 'http://localhost:8080/',
      deleteAfterCompile: true,
      timeout: 600 * 1000,
    }),
  ],
};
```

2. Update project angular.json to point to this custom webpack (under `projects.app.architect.build`):

```
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./custom-webpack.config.js"
            },
```

3. Run `npm run build` to build the app and then `npx http-server` in the app build directory to serve the app on `localhost:8080` -> throw an error

**Expected behavior**

Source maps display correctly if they are uploaded manually via curl:

![image](https://user-images.githubusercontent.com/9100419/103642470-17a6c100-4fa3-11eb-8256-16ee61674634.png)

However if we use just the webpack plugin the maps have the invalid json warning:

![image](https://user-images.githubusercontent.com/9100419/103642510-24c3b000-4fa3-11eb-9e99-5f64d59197ed.png)

**Desktop (please complete the following information):**
 - OS: MacOs 10.15.6 Node v14.15.3
- AppSignal Webpack Plugin 1.1.0 (latest in node)

**Additional context**

I spoke to AppSignal support and they said that the issue appeared to be that the plugin is uploading both the `.js` and the `.map` files so it is trying to parse the sourcemap from the actual javascript code.

**Comment by zbarbuto** [comment]
Looking at the source it would appear that the uploader is testing for both `.js` and `.map` to upload - should probably only test for `.map`

https://github.com/appsignal/appsignal-javascript/blob/develop/packages/webpack/src/index.ts#L104-L106

**Comment by xadamy** [comment]
Good catch @zbarbuto! Opened #462 with a fix, which I'll push out ASAP! 👍
