### ISSUE TITLE
Majority of Errors appear as 'Error'

### ISSUE THREAD

**Issue by zbarbuto** [appsignal/appsignal-javascript#463]
**Is your feature request related to a problem? Please describe.**

In a typical javascript application - any unexpected error is thrown as an instance of `Error`. 

As a result - (I believe because of the [use of `error.name`](https://github.com/appsignal/appsignal-javascript/blob/develop/packages/javascript/src/span.ts#L45) in the error sending) the AppSignal dashboard typically ends up with a single Error type:

![image](https://user-images.githubusercontent.com/9100419/103866952-7fc9e400-5116-11eb-9e56-fe933432bf02.png)

(note in the above example there are actually about half-a-dozen *different* errors in here but they are all listed as `Error` so we have 96 ocurrences)

This isn't particularly useful for several reasons:
1. You can't comment on errors individually
2. You can't fully close individual errors (they are all just filed under `Error`
3. You can't see a proper count of error ocurrences

**Describe the solution you'd like**
I would propose adding additional context to the error that is sent - whether it is a (truncated) version of the error message or the file that the error occurred in. Anything that would give a bit more information on the dashboard.

I would even value this as an "opt-in" feature if you had to manually enable some sort of `additionalErrorContext` option or allow providing a custom function to extract the error name and message for extra customisation options.

I would willing to make a PR for this feature but wanted to get some thoughts from @xadamy and the other AppSignal devs as to whether this sort of functionality would be welcome.

**Comment by xadamy** [comment]
@zbarbuto Thanks for submitting this issue! This isn't a library side issue, unfortunately. This is the way our processor groups things, so it's not something we can add functionality for o the library side. Rest assured that this is currently being looked at and we'll have some big improvements in this area soon.

**Comment by zbarbuto** [comment]
Ok thanks for the info.  I just made the assumption that because `(new Error()).name` was `'Error'` that this might have been the cause 😁 

Can't wait to hear some news in this department.
