### ISSUE TITLE
Webpack Build Errors are Swallowed By Unlink Errors

### ISSUE THREAD

**Issue by zbarbuto** [appsignal/appsignal-javascript#465]
**Describe the bug**

When you run a prod build, if there is a legitimate build error (e.g due to a typing error in your project) the error is hidden and you instead get an error that the map file could not be deleted.

**To Reproduce**

1. Setup a project and connect appsignal webpack (e.g. an Angular project)
2. Intentionally make a build error
3. Run a prod build

**Expected behavior**

That the ts error is shown instead of the map unlink error

**Screenshots**

If I run a build with appsignal webpack installed my build output looks like this:

![image](https://user-images.githubusercontent.com/9100419/104139206-babf6680-53f9-11eb-99db-5b60bb198dd8.png)

If I update `AppSignalPlugin.deleteFiles` in my `node_modules` to add a `catch` to the `unlink` as follows

![image](https://user-images.githubusercontent.com/9100419/104139227-f1957c80-53f9-11eb-98c9-8a8063cf9d0a.png)

I can see the actual error again as normal:

![image](https://user-images.githubusercontent.com/9100419/104139257-2b668300-53fa-11eb-89fa-2800a61d82ba.png)

I have made a PR which adds this catch block here:

https://github.com/appsignal/appsignal-javascript/pull/466

**Comment by tombruijn** [comment]
Hi @zbarbuto, thanks for the issue!
We will look into this, but we don't when yet as we have some other work planned first.

**Comment by zbarbuto** [comment]
@tombruijn I believe it's a relatively simple fix - have a PR for it #466

**Comment by tombruijn** [comment]
@zbarbuto thanks for the PR! I'm still trying to get a test setup where this works in before I review. I hit a dead end and have to start over unfortunately.

**Comment by tombruijn** [comment]
@zbarbuto I'm in the position to test it now (finally), but I'm having some trouble reproducing the issue. If I create a syntax error in a plain JavaScript file it halts the entire build, and doesn't get to the part where it deletes files.

I see you're using typescript? Should I as well? Or can you also reproduce it on a non-typescript project/file?

Can you provide an example file that would fail to compile?

**Comment by zbarbuto** [comment]
Yes, I am using TypeScript. Specifically Angular with custom webpack build (so that I can add the AppSignal Plugin).

Sure thing - I have created a sample repro with the reproduction:

https://github.com/zbarbuto/appsignal-465

The README file has steps to install, build (produce the issue above) and "fix" (show the actual compile error expected)

**Comment by tombruijn** [comment]
Thanks! I'm going to take a look!

**Comment by tombruijn** [comment]
@zbarbuto Amazing! I used your example app to test your PR and I see how it goes wrong now. Thanks for the wait and the help getting this all working and reproducible. We're going to look at when to release this update along with #468. 

Here's the output from `yarn`. I used yarn to test this in our test setup as the webpack package uses yarn as well. It was easier to test that way for me:

```
⚠️ [AppsignalPlugin]: unable to delete 'main.js.map. File does not exist. it may not have been created due to a build error.
⚠️ [AppsignalPlugin]: unable to delete 'polyfills.js.map. File does not exist. it may not have been created due to a build error.
⚠️ [AppsignalPlugin]: unable to delete 'runtime.js.map. File does not exist. it may not have been created due to a build error.
⚠️ [AppsignalPlugin]: unable to delete 'styles.css.map. File does not exist. it may not have been created due to a build error.
⚠️ [AppsignalPlugin]: unable to delete 'vendor.js.map. File does not exist. it may not have been created due to a build error.

Error: src/app/app.component.ts:11:3 - error TS2322: Type 'string' is not assignable to type 'boolean'.

11   brokenValue: boolean = 'string';
     ~~~~~~~~~~~
```
