### ISSUE TITLE
create-react-app sourcemaps support?

### ISSUE THREAD

**Issue by sergiotapia-papa** [appsignal/appsignal-javascript#469]
How can I integrate AppSignal into my very vanilla create-react-app sourcemaps? Anyone accomplish this? Appreciate the insight.

**Comment by shairyar** [comment]
Hi @sergiotapia-papa, 

Could you please explain a bit more what you are trying to do? Are you running into sourcemap upload issues? Did you check out the docs on [sourcemap](https://docs.appsignal.com/front-end/sourcemaps.html)?

**Comment by tombruijn** [comment]
I am getting the idea that this is not possible in a standard create-react-app 🤔 (Disclaimer: I am very unfamiliar with the Node.js ecosystem, feel free to shoot holes in this)

I am trying to set up a create-react-app in our test setups repository (not pushed yet), but I can't customize the webpack.

I looked if this was possible and the create-react-app docs mention no way to customize the config of the react-scripts. You either need to "eject" the create-react-app package and manage _all_ the config yourself, but they recommend [to fork react-scripts and any other packages you need](https://create-react-app.dev/docs/alternatives-to-ejecting) in case you want to customize any config 😳.

I found [react-app-rewired](https://github.com/timarney/react-app-rewired) as a layer on top of create-create-app that does allow customization of webpack config and came up with the implementation below, but that just hangs my development server forever. It works without our plugin so it probably goes wrong there.

```js
# config-overrides.js
const { AppsignalPlugin } = require("@appsignal/webpack")

module.exports = function override(config, env) {
  return {
    ...config,
    plugins: [
      ...config.plugins,
      new AppsignalPlugin({
        // required
        apiKey: "KEY",
        release: "REVISON",
        appName: "react",
        environment: "development",
        urlRoot: "http://localhost:4001/",
        deleteAfterCompile: false
      })
    ],
    devtool: "source-map"
  }
}
```

I hope this insight so far helps with the ways how it does not work.

**Comment by sergiotapia-papa** [comment]
For would be Googlers, CRA has sourcemaps out of the box. All I needed to do was add the revision key to my appsignal configuration. Thanks for the help guys!

**Comment by tombruijn** [comment]
Are you then using the public sourcemaps @sergiotapia-papa ?
