### ISSUE TITLE
Grouping of Appsignal error types

### ISSUE THREAD

**Issue by hbarrientosg** [appsignal/appsignal-javascript#479]
**Is your feature request related to a problem? Please describe.**
Right now javascript reporting on Appsignal is base on name of the Exception for grouping errors. 
Ex:
<img width="1195" alt="Screenshot 2021-06-02 at 12 24 37" src="https://user-images.githubusercontent.com/1461577/120464734-8bf05f80-c39d-11eb-86d5-4ae8f63c8797.png">

Javascript only have a few type error Objects `Error, RangeError, ReferenceError, SyntaxError, TypeError, URIError, EvalError ` but most of errors falls on `Error and TypeError`.

The problem for us is difficulty to track which error are relevant to be fix on our apps. See image above with 25K.

**Describe the solution you'd like**
Include the message next to the type of error in the error name.

<img width="1050" alt="Screenshot 2021-06-03 at 10 03 38" src="https://user-images.githubusercontent.com/1461577/120609995-08914580-c453-11eb-8193-0c1bc0c79237.png">

**Comment by thijsc** [comment]
Thanks for the pull! We are working on a new approach for this and will let you know once there's something to test.

**Comment by hbarrientosg** [comment]
Hello, Is there any progress in this issue or should I close it?

**Comment by thijsc** [comment]
We just released backtrace based grouping for Node and Elixir. We're planning to also bring this to the frontend, but we don't have a timeline for that yet.

**Comment by tombruijn** [comment]
Related issue in https://github.com/appsignal/appsignal-javascript/issues/558

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700118466

**Comment by tombruijn** [comment]
This was shipped some time ago. It's possible to change the frontend error grouping in the [app settings](https://appsignal.com/redirect-to/app?to=edit) in the "Error grouping strategy" box and the "Frontend error grouping strategy" drop down. Closing.
