### ISSUE TITLE
Update react peerDependency in @appsignal/react 

### ISSUE THREAD

**Issue by codyduval** [appsignal/appsignal-javascript#481]
`@appsignal/react@1.0.7` has a peerDependency  for `react` of `^16.8.6`, while `react` is currently at `17.0.2`. Any reason the peerDependency can't be bumped?

**Comment by tombruijn** [comment]
Hi @codyduval, we haven't had time to test with the latest version of react yet, so we didn't update it yet. I've put it on our todo list.

**Comment by hubertlepicki** [comment]
@tombruijn any joy?

**Comment by tombruijn** [comment]
@hubertlepicki Not yet. Yesterday the team decided the blocker on this is holding up a lot of work so we've put it on our immediate roadmap. When the blocker (the CI build) is resolved we can update this dependency and test it with more confidence.

**Comment by smt116** [comment]
@tombruijn any news on this?

**Comment by tombruijn** [comment]
We test against React 17 now. I think we didn't update the version specifier. Let me create a PR.

**Comment by tombruijn** [comment]
@codyduval @hubertlepicki @smt116  I've just published `@appsignal/react@1.0.15` that should allow for it to be installed with React 17.
