### ISSUE TITLE
Redux breadcrumb plugin

### ISSUE THREAD

**Issue by aberonni** [appsignal/appsignal-javascript#483]
**Is your feature request related to a problem? Please describe.**
When thinking about [breadcrumb plugins](https://docs.appsignal.com/front-end/breadcrumbs.html#plugins) and our application, an obvious use case for us would be to sync the actions of our redux store with the breadcrumbs. Then it would be a lot easier for us to reproduce the errors as we see them on appsignal.

**Describe the solution you'd like**
A new plugin `@appsignal/plugin-breadcrumbs-redux`
(I normally wouldn't just ask for something without trying to build it first myself, but the docs said to reach out with plugin requests 😄 )

**Describe alternatives you've considered**
Manually adding a middleware to our redux store to add a breadcrumb for every action

**Comment by shairyar** [comment]
Hey @aberonni we will discuss this and get back to you.

**Comment by shairyar** [comment]
Hey, @aberonni Thanks for the idea! This is not in the pipeline right now, but feel free to work on it at your end. If you have anything please share the solution with us so we have a better idea of your requirements.

I'm going to close this issue and track it in our private feature tracker. Feel free to comment and reopen on this issue if you wish to share anything.
