### ISSUE TITLE
Handle error events and objects without message property in setError

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-javascript#532]
## Background

We received a [bug report](https://github.com/appsignal/appsignal-javascript/issues/531) about events being reported as errors automatically in the React integration.

## The problem

The [React's ErrorBoundary](https://github.com/appsignal/appsignal-javascript/blob/main/packages/react/src/ErrorBoundary.tsx) we provide, moves every Error passed to `componentDidCatch`, into `setError`. Sometimes, these errors are events such as [`CloseEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent). The [`setError`](https://github.com/appsignal/appsignal-javascript/blob/main/packages/javascript/src/span.ts#L41-L60) function tries to access the `message` property of every error moved. If not accessible/non-existing, it sets a string informing that something that might not be an error has been reported as one. This string message calls `JSON.stringify()` for the non-error instance; this is not a good practice as some properties are missed while parsing, and the object ends up looking like: `"{"isTrusted":true}"`.

## The proposal(s)

- Don't treat events as errors unless their type is `error`.
- If the object is an `Event` and its type is `error`, don't write the information message and use its properties instead.
- Fix the `JSON.stringify()` call to include all the relevant properties.

**Comment by tombruijn** [comment]
I've updated the react app in https://github.com/appsignal/test-setups/pull/46 to actually test the error boundary tracking errors.
