### ISSUE TITLE
Allow to update error properties in decorators and overrides

### ISSUE THREAD

**Issue by romaricpascal** [appsignal/appsignal-javascript#558]
To get a more relevant grouping of errors (as most are just `Error`), I've had to set the error name to be `<error.name>: <error.message>`. This led to a bit of workaround:

```js
/**
 * AppSignal groups issues by `name`, but JS Errors
 * are not as typed as Ruby's so they'll mostly end
 * up with an "Error" name. Instead, the actual message
 * will get us clearer grouping
 * @return Function
 */
function errorGroupingDecorator(span) {
  const error = span.serialize().error;
  return span.setError({
    name: `${error.name}: ${error.message}`,
    message: error.message,
    // Destructuring the error leads to missing stacktrace
    // as it seems the `error` object expects a `stack` property
    // as a String, unlike what's described in the docs
    // https://docs.appsignal.com/front-end/span.html#span-seterror-error-error-object
    stack: error.backtrace.join('\n'),
  });
}
```

It would have been great to either:
 - just be able to override the `name` property of the error using `updateError({name: 'New name'})` or even `setName` to explicitely control the grouping.
 - or be able to update the error before it gets processed (I guess I could always wrapped the handler installed on Stimulus' `errorHandler`, `window.onerror` and `window.onunhandledrejection`, but that may break things if there's other code handling the errors that way)
 - or be able to at least deconstruct the existing error (`setError({...error, name: 'New name'})`). Here it seems `setError` completely overrides the `backtrace` even if the error object already provides one. I'm guessing that would be [a change for `getStacktrace`](https://github.com/appsignal/appsignal-javascript/blob/ba65c6445c2c69aa8efec8e5aa307b0edd3b5d8f/packages/core/src/utils/stacktrace.ts#L8)

**Comment by tombruijn** [comment]
Hi @romaricpascal,

We don't this automatically because errors can have unique messages that lead to the generation of a lot of errors for your app on AppSignal.com. We're trying to find a middleground for this.

I'm going to close this issue and link it to the other related issue: https://github.com/appsignal/appsignal-javascript/issues/479
