### ISSUE TITLE
Build broken against React 18

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-javascript#564]
The CI build is broken again react@latest. We should see what's broken and fix it.

https://appsignal.semaphoreci.com/workflows/ea3369ec-cbd0-491f-a087-23ac1c6c4566?pipeline_id=3ec8f69d-5655-458e-bc10-ff11e168a8a5

Blocks #563

**Comment by tombruijn** [comment]
Not sure when this broke because there was no scheduled build set for the JavaScript repo. I've configured that now.

**Comment by tombruijn** [comment]
Looks like React version 18 is released and our package is locked at `< 18`

https://github.com/appsignal/appsignal-javascript/blob/5544713654fecd92d31b07bd0b6576f28ac1b9af/packages/react/package.json#L29

**Comment by luismiramirez** [comment]
Tried to add it to the matrix after receiving the notification of the release of v18.1 here: https://github.com/appsignal/appsignal-javascript/commit/1fabeb3863464fb2d1f5b50cd32a517e089581d1

I had to update the testing library to get rid of the first error described in this issue, and then it threw a new error:

https://appsignal.semaphoreci.com/jobs/95364096-c361-44ce-bbf2-c818301dbf7c

This requires further investigation cause how our ErrorBoundary works may need a change for v18

**Comment by maltesa** [comment]
While this is open, I'm using a "custom" ErrorBoundary as a replacement:

```tsx
import { config } from '@/lib/config'
import Appsignal from '@appsignal/javascript'
import { Component, ErrorInfo, ReactNode } from 'react'

export const appsignal = new Appsignal({
  key: config.appsignalFrontendKey,
  revision: config.revision,
})

interface Props {
  action?: string
  children: ReactNode
  fallback?: (error: Error) => JSX.Element
  tags?: { [key: string]: string }
}

interface State {
  error?: Error
}

export class ErrorBoundary extends Component<Props, State> {
  public state: State = {
    error: undefined,
  }

  public static getDerivedStateFromError(error: Error): State {
    // Update state so the next render will show the fallback UI.
    return { error }
  }

  public componentDidCatch(error: Error, _errorInfo: ErrorInfo) {
    const { action, tags = {} } = this.props
    const span = appsignal.createSpan()

    span.setError(error).setTags({ framework: 'React', ...tags })

    if (action && action !== '') span.setAction(action)

    appsignal.send(span)
  }

  public render() {
    if (this.state.error) {
      return this.props.fallback ? this.props.fallback(this.state.error) : null
    }

    return this.props.children
  }
}

```

**Comment by tombruijn** [comment]
The broken build is very annoying. We can disable the react 18 build for now while it's broken. And then pick up this issue.

**Comment by luismiramirez** [comment]
Hi @maltesa!

Doesn't it work by default for you with React 18 unless you make that modification to `componentDidCatch`? It worked for us in our tests without changing anything.

**Comment by maltesa** [comment]
Just tried again with the ErrorBoundary from  `@appsignal/react` and it works flawlessly as far as I can see. So no, “that modification” is not necessary.

**Comment by luismiramirez** [comment]
Thanks for answering @maltesa! 

I created an issue to cover your suggestion: https://github.com/appsignal/appsignal-javascript/issues/568.

You can keep track of the request from there.
