### ISSUE TITLE
React 18.2.0 and later not allowed in peer dependencies for @appsignal/react

### ISSUE THREAD

**Issue by ragibsm** [appsignal/appsignal-javascript#576]
Currently in peer dependencies for @appsignal/react, React version is allowed up to 18.1.0. I'm facing an issue because of this during installation since I'm using 18.2.0 on a project level. Could you update peer dependencies and allow newer versions of React for @appsignal/react package?

**Comment by unflxw** [comment]
Hi @ragibsm,

Thank you for reporting this issue! This issue has been fixed in [`@appsignal/react` version `1.0.21`](https://www.npmjs.com/package/@appsignal/react). If the issue persists after updating, feel free to reopen the issue.
