### ISSUE TITLE
Peer dependency warning when using Stimulus ^3.0

### ISSUE THREAD

**Issue by psbordjukov** [appsignal/appsignal-javascript#593]
**Describe the bug**

Getting the following warning when calling `yarn`
```
warning " > @appsignal/stimulus@1.0.15" has incorrect peer dependency "stimulus@^1.1.1".
```
Please consider changing https://github.com/appsignal/appsignal-javascript/blob/bc5c0a81fdd9894ccd87f0bdc15e8b9d5f35fb20/packages/stimulus/package.json#L28 to `"@hotwired/stimulus": ">=1.1.1"`.

**To Reproduce**
1. Have the following in your `package.json`:
    ```json
    {
      "dependencies": {
        "@appsignal/stimulus": "^1.0.15",
        "stimulus": "^3.0"
      }
    }
    ```

3. Call `yarn`
5. See warning

**Expected behavior**
No warning should be emitted

**Comment by unflxw** [comment]
Thanks for reporting this @psbordjukov! Closed by #594, which changes the peer dependency requirements to allow Stimulus 3.2 and above.

`@appsignal/stimulus@1.0.16` has just been released with this change.

**Comment by czj** [comment]
Thank you very much, @unflxw. 

Unfortunately, [@hotwired/stimulus](https://www.npmjs.com/package/@hotwired/stimulus) is the new package name, not "stimulus" anymore, so the warning persists.

**Comment by unflxw** [comment]
Ouch! That one's on me. Thanks for letting us know @czj! Reopening.

**Comment by unflxw** [comment]
Alright, `@appsignal/stimulus@1.0.17` has just been released with a fix for this issue. Thanks for your assistance and patience @czj @psbordjukov!
