### ISSUE TITLE
Implement transport for Electron's `net` module

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-javascript#596]
Implement support for [Electron's `net` module](https://www.electronjs.org/docs/latest/api/net). Its API is modeled after the Node.js `http` and `https` modules, so it should be relatively straightforward to implement a transport based on our existing Node transport. We will also need a way to detect we're in Electron in order to select this transport.

Intercom link: https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/unassigned/conversation/16410700208049?view=List

Slack link: https://appsignal.slack.com/archives/CNPP953E2/p1682952828457279

To do
===

- [ ] Create Electron test setup
- [ ] Implement Electron transport
- [ ] Detect Electron and use Electron transport

**Comment by unflxw** [comment]
Replied to the affected user with a pre-release (`@appsignal/javascript@1.3.27-rc.2`) which may fix their issue. I'm not confident that it will, however. The real solution is likely to implement support for [Electron's `net` module](https://www.electronjs.org/docs/latest/api/net).

**Comment by tombruijn** [comment]
Thanks! Please make a PR for the branch with the prerelease so it's easier to track. Even if you think we'll close it anyway because we should use `net`.

**Comment by unflxw** [comment]
Using `electron-fetch` makes our integration compatible with Electron, even when Node.js is disabled. That makes implementing support for `net` much less of a priority.

As such, this task should be closed when #597 is merged.
