### ISSUE TITLE
Expose client globally

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-javascript#598]
Mentioned here: https://github.com/appsignal/frontend-test-setups/pull/36#discussion_r1211628537

The idea would be to add it to the `globalThis`/`window` object, probably as something like `window.__APPSIGNAL__` -- optionally, also add a static method that looks for it. This could make it easier for people to use it from the console.

**Comment by tombruijn** [comment]
Duplicate of https://github.com/appsignal/appsignal-javascript/issues/533
