### ISSUE TITLE
Allow to set environment in @appsignal/javascript

### ISSUE THREAD

**Issue by tmaier** [appsignal/appsignal-javascript#628]
**Is your feature request related to a problem? Please describe.**

My application has a `staging` and a `production` environment. 
I want to distinguish the frontend errors received by the environment, similar as I do it for my backend app.

**Describe the solution you'd like**

Add it as key to the constructor of `Appsignal`.

```js
const appsignal = new Appsignal({
  key: metaContent('appsignal-key'),
  revision: metaContent('app-version'),
  environment: metaContent('app-environment'),
})
```

**Describe alternatives you've considered**

It seems like the webpack plugin knows about environemts. I am not using webpack.

**Comment by unflxw** [comment]
Hi @tmaier!

It is not possible to implement this in the suggested manner, as the front-end API key is scoped to your current application. You can, however, use a different front-end API key for each application's environment:

```js
CURRENT_ENVIRONMENT = "production";

ENVIRONMENT_KEYS = {
  production: "1234-abcd-efgh-blah",
  development: "5678-efgh-abcd-bleh",
};

const appsignal = new Appsignal({
  key: ENVIRONMENT_KEYS[CURRENT_ENVIRONMENT]
});
```
