### ISSUE TITLE
Add option to ignore errors in "plugin-window-events"

### ISSUE THREAD

**Issue by kostas-pblworks** [appsignal/appsignal-javascript#633]
**Is your feature request related to a problem? Please describe.**

The `plugin-window-events` plugin was created to reduce noise from the main library but the moment someone installs it, automatically gets all the noise. 

**Describe the solution you'd like**

It would be nice to be able to ignore specific errors, something like:

```TS
import { plugin } from '@appsignal/plugin-window-events'

// ...

appsignal.use(plugin({ ignorePattern: [ 'AuthenticationError', /.*AdBlock.*/g ] }))

```

**Describe alternatives you've considered**

**Additional context**

**Comment by tombruijn** [comment]
Hi @kostas-pblworks, you can ignore errors using the [`ignoreErrors` config option](https://docs.appsignal.com/front-end/configuration.html), see also [this guide](https://docs.appsignal.com/guides/filter-data/ignore-errors.html#front-end-javascript).
