### ISSUE TITLE
Apollo errors not logged

### ISSUE THREAD

**Issue by matsimitsu** [appsignal/appsignal-javascript#92]
We used to get errors when our GraphQL endpoint returned a 401 ( https://staging.lol/appsignal/sites/55df0815776f720dee49d101/exceptions/incidents/442 )(internal link)

But now the error is ignored with the following message:

![Screenshot 2019-10-09 at 13 51 14](https://user-images.githubusercontent.com/28408/66479009-e25bac80-ea9b-11e9-931c-472104e7e397.png)

**Comment by xadamy** [comment]
We need to update our CDN settings still.

**Comment by xadamy** [comment]
Closing as the library works as expected. Server issue is https://github.com/appsignal/appsignal-server/issues/5009. We'll document this in https://github.com/appsignal/appsignal-docs/issues/253.
